# Course Materials 
## ML 9/9 Exercise

In [1]:
# str(x) will return a string representing a humanly readable format of the x
# Add two numbers but by concatenation! 

def func2(x, y): 
    """
    I want func2(1,3) to return 13 
    func2(25,59) return 2559
    I want x and y to be either strings or intergers 
    """

    # change input to strings 
    lhs = str(x)   # this represents x a string and assigns the result to the variable "lhs"
    rhs = str(y)
    bigstring = float(lhs + rhs)    # this concatenates the lhs and rhs strings into a larger one 
    return (bigstring)   # this changes bigstring to interger 

func2(25, "59")

2559.0

In [2]:
def addNumber(x, y): 
    # write a function that prints "the result of the addition is " (and the actual result)
    # eg. addNumber(1,3) ==> "the result of the addition is 4" 

    result = x + y
    print("the result of the addition is " + str(result))
addNumber(1,3)

the result of the addition is 4

In [7]:
import inspect 
import os 
os.path.exists(Fld)
#print(inspect.getsource(highlight_min))
print(inspect.getsource(pd.DataFrame))

vars()  # means properties 
dir()   # means functions and funtion is not callable 
[x for x in dir(df) if callable(x)]

NameError: name 'Fld' is not defined

In [8]:
# caveat emptor: 
import numpy as np 
import pandas as pd 
pd.Series([True, True, np.nan, False, False, np.nan]).value_counts()

True     2
False    2
dtype: int64

In [9]:
pd.Series([True, True, np.nan, False, np.nan, False, np.nan]).value_counts(dropna = False)

NaN      3
True     2
False    2
dtype: int64

In [6]:
import missingo
missingo.bar(df)

df.columns
pd.isnull(df).astype(int).aggregate(sum).to_dict()

ModuleNotFoundError: No module named 'missingo'

## API Tracker 


Intended to scrap options data from 2008(after the financial crisis) to 2018(up to date), for building econometrics model of trade. 
*  E.G. the default is to download historical data for all strikes that are 10% below the monthly low and 10% above the monthly high. 

* Source: sandbox.tradier.com

* #### SP Tian
* #### July 10, 2019 



### Stock Track

> **Problem**: Data time range only starts 2019. 

> Another useful link of $99 for the basic plan: https://marketxls.com/marketxls-pricing-one-plan/

In [3]:
import http
import json
import pandas as pd
import calendar
import os
from datetime import timedelta, date
from typing import Dict, List, Tuple
import http.client 

# "Bearer SGOAWJ2qkJ5EmfKnGKDR3ZpgPkho"
# endpoint = '/v1/markets/quotes?symbols=spy'

In [ ]:
api = Tradier("SGOAWJ2qkJ5EmfKnGKDR3ZpgPkho")
print(api.options("put"))

In [ ]:
api = Tradier("SGOAWJ2qkJ5EmfKnGKDR3ZpgPkho")
api.historical_data("googl")
api.historical_data("googl")['history']['day']

## Options API Code

In [ ]:
class Tradier:
    def __init__(self, auth: str, storage_path="data/"):
        self.storage_path = storage_path
        # Request: Market Quotes (https://sandbox.tradier.com/v1/markets/quotes?symbols=spy)
        self.connection = http.client.HTTPSConnection(
            "sandbox.tradier.com", 443, timeout=30)
        # Headers
        self.headers = headers = {"Accept": "application/json",
                                  "Authorization": "Bearer SGOAWJ2qkJ5EmfKnGKDR3ZpgPkho".format(auth)}
    # Send synchronously
    def request(self, endpoint: str):
        self.connection.request("GET", endpoint, None, self.headers)
        try:
            response = self.connection.getresponse()
            content = response.read()
            if int(str(response.status)) == 200:
                return json.loads(bytes.decode(content))
            #return None
        except http.client.HTTPException as e:
            print("Exception during request. ")

    def options(self, symbol: str):
        return Options(self, symbol)

    def historical_data(self, symbol: str):
        endpoint = "/v1/markets/history?symbol={}".format(symbol)
        return self.request(endpoint)

    def load_data(self, symbol: str) -> pd.DataFrame:
        path = self.storage_path + "{}.csv".format(symbol)
        if os.path.exists(path):
            df = pd.read_csv(path)
            df = df.set_index(pd.DatetimeIndex(df["date"]))
            df = df.loc[:, ~df.columns.str.contains('date')]
            df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
            return df
        else:
            try:
                df = pd.DataFrame(self.historical_data(
                    symbol).get("history", {}).get("day", []))
                df = df.set_index(pd.DatetimeIndex(df["date"]))
                df = df.loc[:, ~df.columns.str.contains('date')]
                df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
                df.to_csv(symbol + ".csv")
                return df
            except Exception as e:
                return None

def third_fridays(d, n):
    """Given a date, calculates n next third fridays
   https://stackoverflow.com/questions/28680896/how-can-i-get-the-3rd-friday-of-a-month-in-python/28681097"""
 
    def next_third_friday(d):
        """ Given a third friday find next third friday"""
        d += timedelta(weeks=4)
        return d if d.day >= 15 else d + timedelta(weeks=1)
 
    # Find closest friday to 15th of month
    s = date(d.year, d.month, 15)
    result = [s + timedelta(days=(calendar.FRIDAY - s.weekday()) % 7)]
 
    # This month's third friday passed. Find next.
    if result[0] < d:
        result[0] = next_third_friday(result[0])
 
    for i in range(n - 1):
        result.append(next_third_friday(result[-1]))
 
    return result

In [ ]:
class Options:
    def __init__(self, tradier: Tradier, symbol: str):
        self.api = tradier
        self.symbol = symbol
        self.cache = {}

    def call(self, expiration: date, strike: int) -> pd.DataFrame:
        chain = "{symbol}{y}{m:02d}{d:02d}C{strike:05d}000".format(symbol=self.symbol, y=str(
            expiration.year)[2:], m=expiration.month, d=expiration.day, strike=strike)
        if chain in self.cache:
            return self.cache[chain]
        else:
            df = self.api.load_data(chain)
            self.cache[chain] = df
            return df

    def put(self, expiration: date, strike: int) -> pd.DataFrame:
        chain = "{symbol}{y}{m:02d}{d:02d}P{strike:05d}000".format(symbol=self.symbol, y=str(
            expiration.year)[2:], m=expiration.month, d=expiration.day, strike=strike)
        if chain in self.cache:
            return self.cache[chain]
     
        else:
            df = self.api.load_data(chain)
            self.cache[chain] = df
            return df

        
    def initialize_repository(self):
       
       #Download all of the historical price data for all monthly expirations within a 10%
       #price range of the underlying for that month. This can be manually changed in the code
       #below. By default, this downloads data from 2018 only. 
 
        # historical price data for the underlying, which we will merge in
        data = self.api.load_data(self.symbol)
 
        # calculate monthly high and low for the underlying
        monthly_range = {}
        for m in range(1, 13):
            try:
                x = data[date(2019, m, 1):date(2019, m + 1, 1)]
                monthly_range[m] = dict(low=min(x['low']), high=max(x['high']))
            except:
                # If we don't have data for this month, just extrapolate from the previous month
                monthly_range[m] = dict(
                    low=monthly_range[m - 1]['low'], high=monthly_range[m - 1]['high'])
 
        for m, k in monthly_range.items():
            expiration = third_fridays(date(2018, m, 1), 1)[0]
            # Get all strikes that are 10% below the monthly low and 10% above the monthly high
            strikes = [x for x in range(int(k['low'] * .9), int(k['high'] * 1.1))]
            # Download and save all of the option chains
            for s in strikes:
                self.call(expiration, s)
                self.put(expiration, s)

In [ ]:
name_col = ["symbol", "description", "exch", "last", "change", "volume", 
            "open", "high", "low", "close", "bid", "ask", 
            "change_percentage", "average_volumn", "trade_date", "bid_date"]

stock = pd.read_excel("/Users/apple/Downloads/StockScreener.xlsm"
                      , sheet_name = "Data", )
ticker = list(stock.loc[:, 'Ticker'])

In [ ]:
len(ticker)

In [ ]:
print(api.options("SPY").call(date(2019, 1, 18), 300))

In [ ]:
print(api.options("SPY").call(date(2019, 1, 18), 300))

In [ ]:
api.options("SPY").initialize_repository()

In [ ]:
class Tradier:
    def __init__(self, auth: str, storage_path="data/"):
        self.storage_path = storage_path
        self.connection = http.client.HTTPSConnection(
            "sandbox.tradier.com", 443, timeout=30)
        self.headers = headers = {"Accept": "application/json",
                                  "Authorization": "Bearer {}".format(auth)}
 
    def request(self, endpoint: str):
        self.connection.request("GET", endpoint, None, self.headers)
        try:
            response = self.connection.getresponse()
            content = response.read()
            if int(str(response.status)) == 200:
                return json.loads(bytes.decode(content))
            return None
        except http.HTTPException as e:
            return e
 
    def options(self, symbol: str):
        return Options(self, symbol)
 
    def historical_data(self, symbol: str):
        endpoint = "/v1/markets/history?symbol={}".format(symbol)
        return self.request(endpoint)
 
    def load_data(self, symbol: str) -> pd.DataFrame:
        path = self.storage_path + "{}.csv".format(symbol)
        if os.path.exists(path):
            df = pd.read_csv(path)
            df = df.set_index(pd.DatetimeIndex(df["date"]))
            df = df.loc[:, ~df.columns.str.contains('date')]
            df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
            return df
        else:
            try:
                df = pd.DataFrame(self.historical_data(
                    symbol).get("history", {}).get("day", []))
                df = df.set_index(pd.DatetimeIndex(df["date"]))
                df = df.loc[:, ~df.columns.str.contains('date')]
                df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
                return df
            except Exception as e:
                print(e)
                return None
 
 
def third_fridays(d, n):
    """Given a date, calculates n next third fridays
   https://stackoverflow.com/questions/28680896/how-can-i-get-the-3rd-friday-of-a-month-in-python/28681097"""
 
    def next_third_friday(d):
        """ Given a third friday find next third friday"""
        d += timedelta(weeks=4)
        return d if d.day >= 15 else d + timedelta(weeks=1)
 
    # Find closest friday to 15th of month
    s = date(d.year, d.month, 15)
    result = [s + timedelta(days=(calendar.FRIDAY - s.weekday()) % 7)]
 
    # This month's third friday passed. Find next.
    if result[0] < d:
        result[0] = next_third_friday(result[0])
 
    for i in range(n - 1):
        result.append(next_third_friday(result[-1]))
 
    return result

In [ ]:
class Options:
    def __init__(self, tradier: Tradier, symbol: str):
        self.api = tradier
        self.symbol = symbol
        self.cache = {}
 
    def call(self, expiration: date, strike: int) -> pd.DataFrame:
        chain = "{symbol}{y}{m:02d}{d:02d}C{strike:05d}000".format(symbol=self.symbol, y=str(
            expiration.year)[2:], m=expiration.month, d=expiration.day, strike=strike)
        if chain in self.cache:
            return self.cache[chain]
        else:
            df = self.api.load_data(chain)
            self.cache[chain] = df
            return df
 
    def put(self, expiration: date, strike: int) -> pd.DataFrame:
        chain = "{symbol}{y}{m:02d}{d:02d}P{strike:05d}000".format(symbol=self.symbol, y=str(
            expiration.year)[2:], m=expiration.month, d=expiration.day, strike=strike)
        if chain in self.cache:
            return self.cache[chain]
        else:
            df = self.api.load_data(chain)
            self.cache[chain] = df
            return df
 
    def initialize_repository(self):
        '''
       Download all of the historical price data for all monthly expirations within a 10%
       price range of the underlying for that month. This can be manually changed in the code
       below. By default, this downloads data from 2018 only. Beyond that is an exercise for the reader
       '''
 
        # historical price data for the underlying, which we will merge in
        data = self.api.load_data(self.symbol)
 
        # calculate monthly high and low for the underlying
        monthly_range = {}
        for m in range(1, 13):
            try:
                x = data[date(2019, m, 1):date(2019, m + 1, 1)]
                monthly_range[m] = dict(low=min(x['low']), high=max(x['high']))
            except:
                # If we don't have data for this month, just extrapolate from the previous month
                monthly_range[m] = dict(
                    low=monthly_range[m - 1]['low'], high=monthly_range[m - 1]['high'])
 
        for m, k in monthly_range.items():
            expiration = third_fridays(date(2018, m, 1), 1)[0]
            # Get all strikes that are 10% below the monthly low and 10% above the monthly high
            strikes = [x for x in range(int(k['low'] * .9), int(k['high'] * 1.1))]
            # Download and save all of the option chains
            for s in strikes:
                self.call(expiration, s)
                self.put(expiration, s)

In [ ]:
api = Tradier("SGOAWJ2qkJ5EmfKnGKDR3ZpgPkho")
api.options("SPY").initialize_repository()

In [ ]:
data = pd.read_csv("MarketDepthSample.csv")

In [ ]:
data.shape

In [ ]:
data.columns

In [ ]:
import date 
daterange = pd.date_range(date(2008,1,1), date(2019,1,1))
daterange

In [ ]:
import quandl 
quandl.ApiConfig.api_key = 'UxW4i2Tk4yJcxzMRqKLt'
quandl.get_table('SHARADAR/SEP', date={'gte':'2008-01-01', 'lte':'2019-01-01'}, 
                 qopts={"columns":['ticker' ,'date','open','high','low','close','volume','dividends']}, 
                paginate=True)

In [ ]:
equity = quandl.get_table('SHARADAR/SEP', date={'gte':'2008-01-01', 'lte':'2019-01-01'})

In [ ]:
sorted(set(equity['ticker']))

In [ ]:
len(equity['ticker'])

## Yahoo Finance Ticker

In [2]:
import unirest 
response = unirest.post(API_URL,
  headers={
    "X-RapidAPI-Key": API_KEY,
    "Content-Type": "application/x-www-form-urlencoded"
  },
  params={
    "parameter": "value"
  }
)

WARNING: The directory '/Users/apple/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/apple/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting unirest
  Downloading https://files.pythonhosted.org/packages/92/da/2149cbd7a8c78f8b76b377379c1bda64ec36cc13315d55f6f7de6d094ac5/Unirest-1.1.7.tar.gz
Collecting poster>=0.8.1 (from unirest)
  Downloading https://files.pythonhosted.org/packages/9f/dc/0683a458d21c3d561ab2f71b4fcdd812bf04e55c54e560b0854cea95610e/poster-0.8.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/apple/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/setup.py'"'"'; __file__='"'"'/private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/setup.py", line 2, in <module>
        import poster
      File "/private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/var/folders/4h/8s1vtfjn6q96ftrjbs27q_k40000gn/T/pip-install-ce3nv1g7/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ModuleNotFoundError: No module named 'unirest'

In [ ]:
response.code # The HTTP status code
response.headers # The HTTP headers
response.body # The parsed response
response.raw_body # The unparsed response

## Quandl API

Import Quandl API Equity Daily Price

In [ ]:
time = pd.read_csv("/Users/apple/Applications/OneDrive/Date_index.csv")
time.shape

In [5]:
import quandl
quandl.ApiConfig.api_key = "UxW4i2Tk4yJcxzMRqKLt"

In [12]:
mydata = ",".join(str(x) for x in SP500)
mytime = "2019-07-20, 2019-07-21, 2019-07-22, 7/23/19, 7/24/19, 7/25/19, 7/26/19, 7/27/19, 7/28/19"

quandl.get_table("SHARADAR/SF1", calendardate = "2019-07-10", ticker = mydata)

Empty DataFrame
Columns: [ticker, dimension, calendardate, datekey, reportperiod, lastupdated, accoci, assets, assetsavg, assetsc, assetsnc, assetturnover, bvps, capex, cashneq, cashnequsd, cor, consolinc, currentratio, de, debt, debtc, debtnc, debtusd, deferredrev, depamor, deposits, divyield, dps, ebit, ebitda, ebitdamargin, ebitdausd, ebitusd, ebt, eps, epsdil, epsusd, equity, equityavg, equityusd, ev, evebit, evebitda, fcf, fcfps, fxusd, gp, grossmargin, intangibles, intexp, invcap, invcapavg, inventory, investments, investmentsc, investmentsnc, liabilities, liabilitiesc, liabilitiesnc, marketcap, ncf, ncfbus, ncfcommon, ncfdebt, ncfdiv, ncff, ncfi, ncfinv, ncfo, ncfx, netinc, netinccmn, netinccmnusd, netincdis, netincnci, netmargin, opex, opinc, payables, payoutratio, pb, pe, pe1, ppnenet, prefdivis, price, ps, ps1, receivables, retearn, revenue, revenueusd, rnd, roa, roe, roic, ros, sbcomp, sgna, ...]
Index: []

[0 rows x 111 columns]

In [13]:
quandl.get_table('SHARADAR/SF1', calendardate='2018-12-31', ticker = mydata)

,ticker,dimension,calendardate,datekey,reportperiod,lastupdated,accoci,assets,assetsavg,assetsc,...,sharesbas,shareswa,shareswadil,sps,tangibles,taxassets,taxexp,taxliabilities,tbvps,workingcapital
None,,,,,,,,,,,,,,,,,,,,,
0,XOM,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-07,-19564000000,346196000000,349610000000,4.797300e+10,...,4233807170,4233807170,NaN,68.546,346196000000,0,9532000000,29856000000,81.769,-9.165000e+09
1,WMT,MRY,2018-12-31,2019-01-31,2019-01-31,2019-09-06,-11542000000,219295000000,214216750000,6.189700e+10,...,2905260059,2929000000,2.945000e+09,175.625,188114000000,0,4281000000,12409000000,64.956,-1.558000e+10
2,VZ,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-08,2370000000,264829000000,264552500000,3.463600e+10,...,4132015101,4128000000,4.132000e+09,31.701,136310000000,0,3584000000,33795000000,32.949,-3.294000e+09
3,V,MRY,2018-12-31,2018-09-30,2018-09-30,2019-07-26,547000000,69225000000,68399000000,1.821600e+10,...,2034251465,2049000000,2.586000e+09,10.058,26473000000,0,2505000000,4618000000,13.034,6.911000e+09
4,UTX,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-26,-9333000000,134211000000,112374500000,3.550300e+10,...,800984201,800400000,8.101000e+08,83.085,59675000000,1646000000,2626000000,0,74.556,4.135000e+09
5,UNH,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-07,-4160000000,152221000000,153372000000,3.869200e+10,...,962034200,963000000,9.830000e+08,234.940,83986000000,0,3562000000,2474000000,87.213,-1.451700e+10
6,TRV,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-23,-1859000000,104233000000,103955500000,NaN,...,264882804,267400000,2.698000e+08,113.246,99951000000,445000000,438000000,0,378.889,NaN
7,PG,MRY,2018-12-31,2018-06-30,2018-06-30,2019-08-06,-14749000000,118310000000,123043500000,2.332000e+10,...,2514599476,2514599476,NaN,26.578,49233000000,0,3465000000,6163000000,19.579,-4.917000e+09
8,PFE,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-08,-11275000000,159422000000,164213000000,4.992600e+10,...,5780474578,5872000000,5.977000e+09,9.136,70800000000,5298000000,706000000,19702000000,12.226,1.806800e+10
9,NKE,MRY,2018-12-31,2018-05-31,2018-05-31,2019-07-23,-92000000,22536000000,23197500000,1.513400e+10,...,1611759392,1623800000,1.659100e+09,22.415,22097000000,2509000000,2392000000,3366000000,13.763,9.094000e+09
10,MSFT,MRY,2018-12-31,2018-06-30,2018-06-30,2019-08-01,-2187000000,258848000000,252361250000,1.696620e+11,...,7683197503,7700000000,7.794000e+09,14.332,215112000000,0,19903000000,32927000000,28.002,1.111740e+11
11,MRK,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-06,-5545000000,82637000000,84712000000,2.587500e+10,...,2600376500,2600376500,NaN,16.265,52953000000,0,2508000000,3673000000,20.364,3.669000e+09
12,MMM,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-26,-6866000000,36500000000,37282000000,1.370900e+10,...,582287135,588500000,6.020000e+08,55.675,23792000000,0,1637000000,243000000,40.971,6.465000e+09
13,MCD,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-06,-2609500000,32811200000,33324050000,4.053200e+09,...,770910250,778200000,7.856000e+08,27.018,30479700000,0,1891800000,3778700000,39.625,1.079700e+09
14,KO,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-25,-12814000000,83216000000,88242000000,2.493000e+10,...,4256513898,4259000000,4.299000e+09,7.480,61629000000,2674000000,1623000000,2765000000,14.460,-3.852000e+09
15,JPM,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-06,-1507000000,2622532000000,2609387500000,NaN,...,3325410725,3396400000,3.414000e+09,32.101,2568183000000,0,8290000000,0,769.816,NaN
16,JNJ,MRY,2018-12-31,2018-12-30,2018-12-30,2019-07-29,-15222000000,152954000000,155161750000,4.603300e+10,...,2681977969,2681500000,2.728700e+09,30.424,74890000000,7640000000,2702000000,16566000000,27.928,1.480300e+10
17,INTC,MRY,2018-12-31,2018-12-29,2018-12-29,2019-07-30,-974000000,127963000000,127693250000,2.878700e+10,...,4564000000,4611000000,4.701000e+09,15.365,91614000000,0,2264000000,6562000000,20.144,1.216100e+10
18,IBM,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-30,-29490000000,123382000000,123069750000,4.914600e+10,...,908793777,912048072,9.163157e+08,87.266,84030000000,5216000000,2619000000,3046000000,93.222,1.091900e+10
19,HD,MRY,2018-12-31,2019-02-03,2019-02-03,2019-08-27,-772000000,44003000000,45521250000,1.852900e+10,...,1129527754,1137000000,1.143000e+09,95.165,41751000000,0,3435000000,656000000,37.411,1.813000e+09
20,GS,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-05,693000000,931796000000,957782750000,NaN,...,371973740,385400000,3.902000e+08,95.008,931796000000,0,2022000000,0,2455.973,NaN
21,GE,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-31,-14414000000,309585000000,330538500000,NaN,...,8698115000,8698115000,NaN,13.982,232958000000,12129000000,583000000,0,26.783,NaN
22,DIS,MRY,2018-12-31,2018-09-29,2018-09-29,2019-08-06,-3097000000,98598000000,98266750000,1.682500e+10,...,1487242596,1499000000,1.507000e+09,39.649,60517000000,0,1663000000,3109000000,40.615,-1.035000e+09
23,DD,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-06,-12394000000,187855000000,188029000000,1.266550e+11,...,764740291,766992000,7.718260e+08,112.096,138704000000,178000000,1489000000,4027000000,182.339,5.334300e+10
24,CVX,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-07,-3544000000,253863000000,256210000000,3.402100e+10,...,1910774369,1910774369,NaN,87.053,249345000000,0,5715000000,18486000000,130.494,6.850000e+09
25,CSCO,MRY,2018-12-31,2018-07-28,2018-07-28,2019-09-05,-849000000,108784000000,121206000000,6.183700e+10,...,4702882494,4837000000,4.881000e+09,10.198,74526000000,3219000000,12929000000,9589000000,15.952,3.480200e+10
26,CAT,MRY,2018-12-31,2018-12-31,2018-12-31,2019-08-01,-1684000000,78509000000,78429750000,3.860300e+10,...,590106711,591400000,5.994000e+08,92.530,70395000000,1439000000,1698000000,0,119.031,1.038500e+10
27,BA,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-24,-15083000000,117359000000,114690500000,8.783000e+10,...,567885369,567885369,NaN,178.076,106090000000,284000000,1144000000,1736000000,186.816,6.240000e+09
28,AXP,MRY,2018-12-31,2018-12-31,2018-12-31,2019-07-23,-2597000000,188602000000,185627750000,NaN,...,854261803,856000000,8.590000e+08,43.208,188602000000,0,1201000000,0,220.329,NaN
29,AAPL,MRY,2018-12-31,2018-09-29,2018-09-29,2019-07-31,-3454000000,365725000000,372304500000,1.313390e+11,...,4829926000,4955377000,5.000109e+09,53.597,365725000000,0,13372000000,0,76.168,1.541000e+10

## Options Correlation 

This file is created for the project 3 of Option Correlation. Even though the size of equity/stock is (9242, 1397), dating from 2014-01-02, the size of options is (), dating only for a month. The purpose of this project is to compare the daily options prices of each company/ticker against the equity price change. 



* **SP Tian** 
* **Aug 1, 2019** 


**def function to judge whether it's at the money within a month 
def a month 
at the money price range **
> weekly options

In [1]:
def plot_corr(df, size=10):
    '''Function plots a graphical correlation matrix for each pair of columns in the dataframe.

    Input:
        df: pandas DataFrame
        size: vertical and horizontal size of the plot'''

    fig, ax = plt.subplots(figsize=(size, size))
    img = ax.matshow(df)
    fig.colorbar(img)
    plt.xticks(range(len(corr.columns)), corr.columns);
    plt.yticks(range(len(corr.columns)), corr.columns);

In [7]:
File = "/Users/apple/Applications/OneDrive/SP500.xlsx"

In [8]:
optionschain = pd.read_excel(File, sheetname = "Options", index_col=None, header=None)

/Users/apple/anaconda3/lib/python3.7/site-packages/pandas/util/_decorators.py:188: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

In [9]:
print(optionschain.shape)
optionschain[0].sample(10)

(103066, 1)

84557    @GWW   190809C00262500
44435    @DE    200320C00160000
53157    @SYY   190802C00071500
22053    @TMO   200117C00260000
52403    @EW    190913C00205000
15164    @NFLX  200619P00300000
44644    @KMB   190823P00133000
98333    @FFIV  190816C00137000
90360    @TTWO  190802P00131000
95410    @APA   190913P00023000
Name: 0, dtype: object

In [10]:
equity = pd.read_excel(File, sheetname = "Equity", index_col='Date')
equity.sample(10)

,MSFT,AMZN,AAPL,GOOGL,GOOG,BRK.B,FB,V,JNJ,JPM,...,HOG,PWR,JEF,MAC,CPRI,JWN,LEG,FL,AMG,MAT
Date,,,,,,,,,,,,,,,,,,,,,
2019-08-02,136.90,1823.24,204.02,1196.32,1193.99,202.67,189.02,177.42,131.07,112.93,...,35.01,33.51,20.17,32.37,33.19,30.79,38.51,39.36,81.12,13.14
2019-07-22,138.43,1985.63,207.22,1139.21,1138.07,204.84,202.32,180.57,128.64,114.27,...,34.28,37.37,20.71,32.03,35.65,28.76,39.53,42.29,87.95,11.72
2019-07-26,141.34,1943.05,207.74,1245.22,1250.41,209.90,199.75,183.69,130.73,116.22,...,35.90,37.80,21.60,32.77,36.08,30.50,39.31,43.24,90.05,14.17
2019-08-09,137.71,1807.58,200.99,1188.90,1188.01,199.05,187.85,179.05,132.04,109.74,...,33.84,34.31,19.56,30.50,31.00,29.30,38.98,40.92,80.02,11.31
2019-08-29,138.12,1786.40,209.01,1194.24,1192.85,203.20,185.57,181.17,128.24,109.22,...,31.41,33.53,18.66,28.20,26.55,29.13,37.26,35.84,75.78,9.51
2019-07-29,141.03,1912.45,209.68,1241.84,1239.41,208.61,195.94,183.21,133.02,115.85,...,35.58,37.91,21.32,33.04,36.30,30.94,38.98,42.54,86.65,14.51
2019-08-05,132.21,1765.13,193.34,1154.75,1152.32,197.73,181.73,168.86,130.16,109.57,...,33.30,32.66,19.27,31.25,31.71,30.20,37.62,38.56,78.99,12.63
2019-08-30,137.86,1776.29,208.74,1190.53,1188.10,203.41,185.67,180.82,128.36,109.86,...,31.90,33.90,18.64,28.53,26.38,28.97,37.19,36.19,76.63,9.80
2019-08-08,138.89,1832.89,203.43,1206.19,1204.80,200.52,190.16,179.90,131.68,109.86,...,34.35,33.66,19.93,30.98,32.69,30.13,39.53,40.53,81.12,13.43
2019-08-01,138.06,1855.32,208.43,1211.78,1209.01,201.71,192.73,179.17,130.29,112.94,...,34.84,35.51,20.58,32.26,33.97,30.83,38.87,39.34,82.74,13.59

In [11]:
SP500 = pd.read_excel("/Users/apple/Applications/OneDrive/SP500.xlsx", sheetname = "Ticker", index_col=None, header=None)
SP500 = SP500[0]
SP500.shape

(505,)

In [ ]:
def color_negative_red(val):
    """
    Takes a scalar and returns a string with
    the css property `'color: red'` for negative
    strings, black otherwise.
    """
    color = 'red' if val < 0 else 'black'
    return 'color: %s' % color

corr_call.style.applymap(color_negative_red)

In [ ]:
def highlight_max(s):
    '''
    highlight the maximum in a Series yellow.
    '''
    is_max = s == s.max()
    return ['background-color: yellow' if v else '' for v in is_max]

corr_call.style.apply(highlight_max)

In [ ]:
corr_df = equity.corr(method='pearson')
corr_put = put_op.corr(method='pearson')
corr_call = call_op.corr(method='pearson')

corr_put.style.applymap(color_negative_red).apply(highlight_max)

Style functions should return strings with one or more CSS attribute: value delimited by semicolons. Use

1. Styler.applymap(func) for elementwise styles
2. Styler.apply(func, axis=0) for columnwise styles
3. Styler.apply(func, axis=1) for rowwise styles
4. Styler.apply(func, axis=None) for tablewise styles

In [ ]:
cm = sns.light_palette("green", as_cmap=True)
corr_put.style.set_caption('Colormaps, with a caption.').background_gradient(cmap=cm)   # create heatmap using ```background_gradient```

In [ ]:
# Uses the full color range
corr_put.loc[:4].style.background_gradient(cmap='viridis')

# Compress the color range
(df.loc[:4]
    .style
    .background_gradient(cmap='viridis', low=.5, high=0)
    .highlight_null('red'))

#corr.style.background_gradient(cmap, axis=1)\
#    .set_properties(**{'max-width': '80px', 'font-size': '10pt'})\
#    .set_caption("Hover to magify")\
#    .set_precision(2)\
#    .set_table_styles(magnify())

# corr_put.style.highlight_null().render().split('\n')[:10]

In [ ]:
# Hover to highlight in html 

from IPython.display import HTML
def hover(hover_color="#ffff99"):
    return dict(selector="tr:hover",
                props=[("background-color", "%s" % hover_color)])

styles = [
    hover(),
    dict(selector="th", props=[("font-size", "150%"),
                               ("text-align", "center")]),
    dict(selector="caption", props=[("caption-side", "bottom")])
]
html = (corr_call.style.set_table_styles(styles)
          .set_caption("Hover to highlight."))
html

In [ ]:
from IPython.html import widgets
@widgets.interact
def f(h_neg=(0, 359, 1), h_pos=(0, 359), s=(0., 99.9), l=(0., 99.9)):
    return corr_put.style.background_gradient(
        cmap=sns.palettes.diverging_palette(h_neg=h_neg, h_pos=h_pos, s=s, l=l,
                                            as_cmap=True)
    )

def magnify():
    return [dict(selector="th",
                 props=[("font-size", "4pt")]),
            dict(selector="td",
                 props=[('padding', "0em 0em")]),
            dict(selector="th:hover",
                 props=[("font-size", "12pt")]),
            dict(selector="tr:hover td:hover",
                 props=[('max-width', '200px'),
                        ('font-size', '12pt')])
]

In [ ]:
np.random.seed(25)
cmap = cmap=sns.diverging_palette(5, 250, as_cmap=True)
bigdf = pd.DataFrame(np.random.randn(20, 25)).cumsum()

bigdf.style.background_gradient(cmap, axis=1)\
    .set_properties(**{'max-width': '80px', 'font-size': '1pt'})\
    .set_caption("Hover to magnify")\
    .set_precision(2)\
    .set_table_styles(magnify())

In [ ]:
cmap = cmap=sns.diverging_palette(5, 250, as_cmap=True)
corr_put.style.background_gradient(cmap, axis=1)\
    .set_properties(**{'max-width': '80px', 'font-size': '1pt'})\
    .set_caption("Hover to magnify")\
    .set_precision(2)\
    .set_table_styles(magnify())

In [ ]:
cmap = cmap=sns.diverging_palette(5, 250, as_cmap=True)
corr_call.style.background_gradient(cmap, axis=1)\
    .set_properties(**{'max-width': '80px', 'font-size': '1pt'})\
    .set_caption("Hover to magnify")\
    .set_precision(2)\
    .set_table_styles(magnify())

In [ ]:
Octchain = []
for x in optionchain[0]: 
    if "191018" in x: 
        Octchain.append(x)

Sepchain = []
for x in optionchain[0]: 
    if "190920" in x: 
        Sepchain.append(x)

In [ ]:
Octchain = pd.DataFrame(Octchain)
Octchain.to_excel("Option Chain Oct.xlsx")

## Future Purpose

In [1]:
def test(corr_dict): 
    keys = np.array(list(corr_dict.keys()))
    indices = np.where(np.array(list(corr_dict.values()).abs()) > 0.9)[0]
    put_output[keys[indices]] = indices 
        #corr_dict[keys[indices]] = indices 
    return keys[indices]

In [2]:
#n = pd.DataFrame(, index = "options", colnames = "equity")
for i in corr_put.keys(): 
    n[i.split(" ")[0][i[1]]] = corr_put[i]
    n.set_value(i[0],i[1],corr_put[i])
    print(n)
    
row = np.array(list(corr_put.values()))
print(pd.DataFrame(row, columns = list(corr_put.keys())))

NameError: name 'corr_put' is not defined